using System;
using System.Collections.Generic;

namespace ClairTourTiny.Infrastructure.Models;

public partial class Oelocation
{
    public string Locationcd { get; set; } = null!;

    public string? Name { get; set; }

    public string Addr1 { get; set; } = null!;

    public string Addr2 { get; set; } = null!;

    public string Addr3 { get; set; } = null!;

    public string City { get; set; } = null!;

    public string State { get; set; } = null!;

    public string Zip { get; set; } = null!;

    public string Country { get; set; } = null!;

    public string Ref1 { get; set; } = null!;

    public string Ref2 { get; set; } = null!;

    public string Ref3 { get; set; } = null!;

    public string Ref4 { get; set; } = null!;

    public string Ref5 { get; set; } = null!;

    public string Ref6 { get; set; } = null!;

    public string Ref7 { get; set; } = null!;

    public string Ref8 { get; set; } = null!;

    public string Phone { get; set; } = null!;

    public string Extension { get; set; } = null!;

    public string Contact { get; set; } = null!;

    public string Frghtmatrix { get; set; } = null!;

    public Guid Primekey { get; set; }

    public Guid MsreplTranVersion { get; set; }

    public string? ShippingAddr1 { get; set; }

    public string? ShippingAddr2 { get; set; }

    public string? ShippingAddr3 { get; set; }

    public string? ShippingCity { get; set; }

    public string? ShippingState { get; set; }

    public string? ShippingZip { get; set; }

    public string? ShippingCountry { get; set; }

    public string? Invoicingprefix { get; set; }

    public int? NextInvoiceSequenceNo { get; set; }

    public string Fax { get; set; } = null!;

    public int? InvoicingTaxGroupId { get; set; }

    public string? WebAddress { get; set; }

    public string? LogoFilename { get; set; }

    public string? MotorCertSignatureFilename { get; set; }

    public string? ShippingStateLong { get; set; }

    public string? LocationPhone { get; set; }

    public string? LocationFax { get; set; }

    public string? SteelCertSignatureFilename { get; set; }

    public string? PublicName { get; set; }

    public string CustomerInvoiceSubFolderFormat { get; set; } = null!;

    public string AutoGeneratedInvoiceNameFormat { get; set; } = null!;

    public string AutoInvoiceGeneration { get; set; } = null!;

    public string Countrycode { get; set; } = null!;

    public string? ShippingCountrycode { get; set; }

    public bool HideHeaderAddress { get; set; }

    public string? AccountsReceivableEmail { get; set; }

    public string? AccountsPayableEmail { get; set; }

    public string? AccountsLogoOverride { get; set; }

    public string? PurchasingEmail { get; set; }

    public string? Currency { get; set; }

    public string? FooterFilename { get; set; }

    public string? QuoteEmail { get; set; }

    public virtual ICollection<AllocatedNewInvoiceNumber> AllocatedNewInvoiceNumbers { get; set; } = new List<AllocatedNewInvoiceNumber>();

    public virtual AutoInvoiceGeneration AutoInvoiceGenerationNavigation { get; set; } = null!;

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual Country CountrycodeNavigation { get; set; } = null!;

    public virtual Currency? CurrencyNavigation { get; set; }

    public virtual ICollection<Glentity> Glentities { get; set; } = new List<Glentity>();

    public virtual InvoicingTaxGroup? InvoicingTaxGroup { get; set; }

    public virtual Country? ShippingCountrycodeNavigation { get; set; }

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}
